-- Externalizes export files: the generated bytes move to local disk or
-- object storage and the row only keeps a storage reference. file_content is
-- retained (nullable) so the startup backfill can read legacy rows; once all
-- legacy rows are migrated, the column can be dropped in a later migration.
ALTER TABLE export_tasks
    ADD COLUMN file_path VARCHAR(500) NULL AFTER file_name;
